// Generated by gencpp from file rb_ui/rb_ArrayAndBool.msg
// DO NOT EDIT!


#ifndef RB_UI_MESSAGE_RB_ARRAYANDBOOL_H
#define RB_UI_MESSAGE_RB_ARRAYANDBOOL_H

#include <ros/service_traits.h>


#include <rb_ui/rb_ArrayAndBoolRequest.h>
#include <rb_ui/rb_ArrayAndBoolResponse.h>


namespace rb_ui
{

struct rb_ArrayAndBool
{

typedef rb_ArrayAndBoolRequest Request;
typedef rb_ArrayAndBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rb_ArrayAndBool
} // namespace rb_ui


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rb_ui::rb_ArrayAndBool > {
  static const char* value()
  {
    return "e9689b9c66e8f3509d77fd7da204e850";
  }

  static const char* value(const ::rb_ui::rb_ArrayAndBool&) { return value(); }
};

template<>
struct DataType< ::rb_ui::rb_ArrayAndBool > {
  static const char* value()
  {
    return "rb_ui/rb_ArrayAndBool";
  }

  static const char* value(const ::rb_ui::rb_ArrayAndBool&) { return value(); }
};


// service_traits::MD5Sum< ::rb_ui::rb_ArrayAndBoolRequest> should match 
// service_traits::MD5Sum< ::rb_ui::rb_ArrayAndBool > 
template<>
struct MD5Sum< ::rb_ui::rb_ArrayAndBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rb_ui::rb_ArrayAndBool >::value();
  }
  static const char* value(const ::rb_ui::rb_ArrayAndBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rb_ui::rb_ArrayAndBoolRequest> should match 
// service_traits::DataType< ::rb_ui::rb_ArrayAndBool > 
template<>
struct DataType< ::rb_ui::rb_ArrayAndBoolRequest>
{
  static const char* value()
  {
    return DataType< ::rb_ui::rb_ArrayAndBool >::value();
  }
  static const char* value(const ::rb_ui::rb_ArrayAndBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rb_ui::rb_ArrayAndBoolResponse> should match 
// service_traits::MD5Sum< ::rb_ui::rb_ArrayAndBool > 
template<>
struct MD5Sum< ::rb_ui::rb_ArrayAndBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rb_ui::rb_ArrayAndBool >::value();
  }
  static const char* value(const ::rb_ui::rb_ArrayAndBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rb_ui::rb_ArrayAndBoolResponse> should match 
// service_traits::DataType< ::rb_ui::rb_ArrayAndBool > 
template<>
struct DataType< ::rb_ui::rb_ArrayAndBoolResponse>
{
  static const char* value()
  {
    return DataType< ::rb_ui::rb_ArrayAndBool >::value();
  }
  static const char* value(const ::rb_ui::rb_ArrayAndBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RB_UI_MESSAGE_RB_ARRAYANDBOOL_H
