// Generated by gencpp from file rb_ui/rb_DoubleBool.msg
// DO NOT EDIT!


#ifndef RB_UI_MESSAGE_RB_DOUBLEBOOL_H
#define RB_UI_MESSAGE_RB_DOUBLEBOOL_H

#include <ros/service_traits.h>


#include <rb_ui/rb_DoubleBoolRequest.h>
#include <rb_ui/rb_DoubleBoolResponse.h>


namespace rb_ui
{

struct rb_DoubleBool
{

typedef rb_DoubleBoolRequest Request;
typedef rb_DoubleBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rb_DoubleBool
} // namespace rb_ui


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rb_ui::rb_DoubleBool > {
  static const char* value()
  {
    return "f33163c172ac2891a975961a1d79e44e";
  }

  static const char* value(const ::rb_ui::rb_DoubleBool&) { return value(); }
};

template<>
struct DataType< ::rb_ui::rb_DoubleBool > {
  static const char* value()
  {
    return "rb_ui/rb_DoubleBool";
  }

  static const char* value(const ::rb_ui::rb_DoubleBool&) { return value(); }
};


// service_traits::MD5Sum< ::rb_ui::rb_DoubleBoolRequest> should match 
// service_traits::MD5Sum< ::rb_ui::rb_DoubleBool > 
template<>
struct MD5Sum< ::rb_ui::rb_DoubleBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rb_ui::rb_DoubleBool >::value();
  }
  static const char* value(const ::rb_ui::rb_DoubleBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rb_ui::rb_DoubleBoolRequest> should match 
// service_traits::DataType< ::rb_ui::rb_DoubleBool > 
template<>
struct DataType< ::rb_ui::rb_DoubleBoolRequest>
{
  static const char* value()
  {
    return DataType< ::rb_ui::rb_DoubleBool >::value();
  }
  static const char* value(const ::rb_ui::rb_DoubleBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rb_ui::rb_DoubleBoolResponse> should match 
// service_traits::MD5Sum< ::rb_ui::rb_DoubleBool > 
template<>
struct MD5Sum< ::rb_ui::rb_DoubleBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rb_ui::rb_DoubleBool >::value();
  }
  static const char* value(const ::rb_ui::rb_DoubleBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rb_ui::rb_DoubleBoolResponse> should match 
// service_traits::DataType< ::rb_ui::rb_DoubleBool > 
template<>
struct DataType< ::rb_ui::rb_DoubleBoolResponse>
{
  static const char* value()
  {
    return DataType< ::rb_ui::rb_DoubleBool >::value();
  }
  static const char* value(const ::rb_ui::rb_DoubleBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RB_UI_MESSAGE_RB_DOUBLEBOOL_H
