// Generated by gencpp from file hirop_msgs/robotError.msg
// DO NOT EDIT!


#ifndef HIROP_MSGS_MESSAGE_ROBOTERROR_H
#define HIROP_MSGS_MESSAGE_ROBOTERROR_H

#include <ros/service_traits.h>


#include <hirop_msgs/robotErrorRequest.h>
#include <hirop_msgs/robotErrorResponse.h>


namespace hirop_msgs
{

struct robotError
{

typedef robotErrorRequest Request;
typedef robotErrorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robotError
} // namespace hirop_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hirop_msgs::robotError > {
  static const char* value()
  {
    return "e0f6e99a383cee4fd92b0a43632c9079";
  }

  static const char* value(const ::hirop_msgs::robotError&) { return value(); }
};

template<>
struct DataType< ::hirop_msgs::robotError > {
  static const char* value()
  {
    return "hirop_msgs/robotError";
  }

  static const char* value(const ::hirop_msgs::robotError&) { return value(); }
};


// service_traits::MD5Sum< ::hirop_msgs::robotErrorRequest> should match 
// service_traits::MD5Sum< ::hirop_msgs::robotError > 
template<>
struct MD5Sum< ::hirop_msgs::robotErrorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hirop_msgs::robotError >::value();
  }
  static const char* value(const ::hirop_msgs::robotErrorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hirop_msgs::robotErrorRequest> should match 
// service_traits::DataType< ::hirop_msgs::robotError > 
template<>
struct DataType< ::hirop_msgs::robotErrorRequest>
{
  static const char* value()
  {
    return DataType< ::hirop_msgs::robotError >::value();
  }
  static const char* value(const ::hirop_msgs::robotErrorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hirop_msgs::robotErrorResponse> should match 
// service_traits::MD5Sum< ::hirop_msgs::robotError > 
template<>
struct MD5Sum< ::hirop_msgs::robotErrorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hirop_msgs::robotError >::value();
  }
  static const char* value(const ::hirop_msgs::robotErrorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hirop_msgs::robotErrorResponse> should match 
// service_traits::DataType< ::hirop_msgs::robotError > 
template<>
struct DataType< ::hirop_msgs::robotErrorResponse>
{
  static const char* value()
  {
    return DataType< ::hirop_msgs::robotError >::value();
  }
  static const char* value(const ::hirop_msgs::robotErrorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIROP_MSGS_MESSAGE_ROBOTERROR_H
