// Generated by gencpp from file hirop_msgs/robotConn.msg
// DO NOT EDIT!


#ifndef HIROP_MSGS_MESSAGE_ROBOTCONN_H
#define HIROP_MSGS_MESSAGE_ROBOTCONN_H

#include <ros/service_traits.h>


#include <hirop_msgs/robotConnRequest.h>
#include <hirop_msgs/robotConnResponse.h>


namespace hirop_msgs
{

struct robotConn
{

typedef robotConnRequest Request;
typedef robotConnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robotConn
} // namespace hirop_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hirop_msgs::robotConn > {
  static const char* value()
  {
    return "e2cc9e9d8c464550830df49c160979ad";
  }

  static const char* value(const ::hirop_msgs::robotConn&) { return value(); }
};

template<>
struct DataType< ::hirop_msgs::robotConn > {
  static const char* value()
  {
    return "hirop_msgs/robotConn";
  }

  static const char* value(const ::hirop_msgs::robotConn&) { return value(); }
};


// service_traits::MD5Sum< ::hirop_msgs::robotConnRequest> should match 
// service_traits::MD5Sum< ::hirop_msgs::robotConn > 
template<>
struct MD5Sum< ::hirop_msgs::robotConnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hirop_msgs::robotConn >::value();
  }
  static const char* value(const ::hirop_msgs::robotConnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hirop_msgs::robotConnRequest> should match 
// service_traits::DataType< ::hirop_msgs::robotConn > 
template<>
struct DataType< ::hirop_msgs::robotConnRequest>
{
  static const char* value()
  {
    return DataType< ::hirop_msgs::robotConn >::value();
  }
  static const char* value(const ::hirop_msgs::robotConnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hirop_msgs::robotConnResponse> should match 
// service_traits::MD5Sum< ::hirop_msgs::robotConn > 
template<>
struct MD5Sum< ::hirop_msgs::robotConnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hirop_msgs::robotConn >::value();
  }
  static const char* value(const ::hirop_msgs::robotConnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hirop_msgs::robotConnResponse> should match 
// service_traits::DataType< ::hirop_msgs::robotConn > 
template<>
struct DataType< ::hirop_msgs::robotConnResponse>
{
  static const char* value()
  {
    return DataType< ::hirop_msgs::robotConn >::value();
  }
  static const char* value(const ::hirop_msgs::robotConnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HIROP_MSGS_MESSAGE_ROBOTCONN_H
