// Generated by gencpp from file rb_ui/rb_ImageArray.msg
// DO NOT EDIT!


#ifndef RB_UI_MESSAGE_RB_IMAGEARRAY_H
#define RB_UI_MESSAGE_RB_IMAGEARRAY_H

#include <ros/service_traits.h>


#include <rb_ui/rb_ImageArrayRequest.h>
#include <rb_ui/rb_ImageArrayResponse.h>


namespace rb_ui
{

struct rb_ImageArray
{

typedef rb_ImageArrayRequest Request;
typedef rb_ImageArrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rb_ImageArray
} // namespace rb_ui


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rb_ui::rb_ImageArray > {
  static const char* value()
  {
    return "3d72f9c5c0957b5aa348eaf6873546dd";
  }

  static const char* value(const ::rb_ui::rb_ImageArray&) { return value(); }
};

template<>
struct DataType< ::rb_ui::rb_ImageArray > {
  static const char* value()
  {
    return "rb_ui/rb_ImageArray";
  }

  static const char* value(const ::rb_ui::rb_ImageArray&) { return value(); }
};


// service_traits::MD5Sum< ::rb_ui::rb_ImageArrayRequest> should match 
// service_traits::MD5Sum< ::rb_ui::rb_ImageArray > 
template<>
struct MD5Sum< ::rb_ui::rb_ImageArrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rb_ui::rb_ImageArray >::value();
  }
  static const char* value(const ::rb_ui::rb_ImageArrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rb_ui::rb_ImageArrayRequest> should match 
// service_traits::DataType< ::rb_ui::rb_ImageArray > 
template<>
struct DataType< ::rb_ui::rb_ImageArrayRequest>
{
  static const char* value()
  {
    return DataType< ::rb_ui::rb_ImageArray >::value();
  }
  static const char* value(const ::rb_ui::rb_ImageArrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rb_ui::rb_ImageArrayResponse> should match 
// service_traits::MD5Sum< ::rb_ui::rb_ImageArray > 
template<>
struct MD5Sum< ::rb_ui::rb_ImageArrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rb_ui::rb_ImageArray >::value();
  }
  static const char* value(const ::rb_ui::rb_ImageArrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rb_ui::rb_ImageArrayResponse> should match 
// service_traits::DataType< ::rb_ui::rb_ImageArray > 
template<>
struct DataType< ::rb_ui::rb_ImageArrayResponse>
{
  static const char* value()
  {
    return DataType< ::rb_ui::rb_ImageArray >::value();
  }
  static const char* value(const ::rb_ui::rb_ImageArrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RB_UI_MESSAGE_RB_IMAGEARRAY_H
