// Generated by gencpp from file rb_ui/robotConnRequest.msg
// DO NOT EDIT!


#ifndef RB_UI_MESSAGE_ROBOTCONNREQUEST_H
#define RB_UI_MESSAGE_ROBOTCONNREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rb_ui
{
template <class ContainerAllocator>
struct robotConnRequest_
{
  typedef robotConnRequest_<ContainerAllocator> Type;

  robotConnRequest_()
    {
    }
  robotConnRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::rb_ui::robotConnRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rb_ui::robotConnRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robotConnRequest_

typedef ::rb_ui::robotConnRequest_<std::allocator<void> > robotConnRequest;

typedef boost::shared_ptr< ::rb_ui::robotConnRequest > robotConnRequestPtr;
typedef boost::shared_ptr< ::rb_ui::robotConnRequest const> robotConnRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rb_ui::robotConnRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rb_ui::robotConnRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rb_ui

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rb_ui::robotConnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rb_ui::robotConnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rb_ui::robotConnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rb_ui::robotConnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rb_ui::robotConnRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rb_ui::robotConnRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rb_ui::robotConnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::rb_ui::robotConnRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::rb_ui::robotConnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rb_ui/robotConnRequest";
  }

  static const char* value(const ::rb_ui::robotConnRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rb_ui::robotConnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::rb_ui::robotConnRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rb_ui::robotConnRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotConnRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rb_ui::robotConnRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::rb_ui::robotConnRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // RB_UI_MESSAGE_ROBOTCONNREQUEST_H
