// Generated by gencpp from file rb_ui/robotError.msg
// DO NOT EDIT!


#ifndef RB_UI_MESSAGE_ROBOTERROR_H
#define RB_UI_MESSAGE_ROBOTERROR_H

#include <ros/service_traits.h>


#include <rb_ui/robotErrorRequest.h>
#include <rb_ui/robotErrorResponse.h>


namespace rb_ui
{

struct robotError
{

typedef robotErrorRequest Request;
typedef robotErrorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robotError
} // namespace rb_ui


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rb_ui::robotError > {
  static const char* value()
  {
    return "e0f6e99a383cee4fd92b0a43632c9079";
  }

  static const char* value(const ::rb_ui::robotError&) { return value(); }
};

template<>
struct DataType< ::rb_ui::robotError > {
  static const char* value()
  {
    return "rb_ui/robotError";
  }

  static const char* value(const ::rb_ui::robotError&) { return value(); }
};


// service_traits::MD5Sum< ::rb_ui::robotErrorRequest> should match 
// service_traits::MD5Sum< ::rb_ui::robotError > 
template<>
struct MD5Sum< ::rb_ui::robotErrorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rb_ui::robotError >::value();
  }
  static const char* value(const ::rb_ui::robotErrorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rb_ui::robotErrorRequest> should match 
// service_traits::DataType< ::rb_ui::robotError > 
template<>
struct DataType< ::rb_ui::robotErrorRequest>
{
  static const char* value()
  {
    return DataType< ::rb_ui::robotError >::value();
  }
  static const char* value(const ::rb_ui::robotErrorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rb_ui::robotErrorResponse> should match 
// service_traits::MD5Sum< ::rb_ui::robotError > 
template<>
struct MD5Sum< ::rb_ui::robotErrorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rb_ui::robotError >::value();
  }
  static const char* value(const ::rb_ui::robotErrorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rb_ui::robotErrorResponse> should match 
// service_traits::DataType< ::rb_ui::robotError > 
template<>
struct DataType< ::rb_ui::robotErrorResponse>
{
  static const char* value()
  {
    return DataType< ::rb_ui::robotError >::value();
  }
  static const char* value(const ::rb_ui::robotErrorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RB_UI_MESSAGE_ROBOTERROR_H
