// Generated by gencpp from file rb_ui/SetEnableSrv.msg
// DO NOT EDIT!


#ifndef RB_UI_MESSAGE_SETENABLESRV_H
#define RB_UI_MESSAGE_SETENABLESRV_H

#include <ros/service_traits.h>


#include <rb_ui/SetEnableSrvRequest.h>
#include <rb_ui/SetEnableSrvResponse.h>


namespace rb_ui
{

struct SetEnableSrv
{

typedef SetEnableSrvRequest Request;
typedef SetEnableSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetEnableSrv
} // namespace rb_ui


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rb_ui::SetEnableSrv > {
  static const char* value()
  {
    return "9a3f214f0cfe55a69bdaec5c37a1e8b9";
  }

  static const char* value(const ::rb_ui::SetEnableSrv&) { return value(); }
};

template<>
struct DataType< ::rb_ui::SetEnableSrv > {
  static const char* value()
  {
    return "rb_ui/SetEnableSrv";
  }

  static const char* value(const ::rb_ui::SetEnableSrv&) { return value(); }
};


// service_traits::MD5Sum< ::rb_ui::SetEnableSrvRequest> should match 
// service_traits::MD5Sum< ::rb_ui::SetEnableSrv > 
template<>
struct MD5Sum< ::rb_ui::SetEnableSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rb_ui::SetEnableSrv >::value();
  }
  static const char* value(const ::rb_ui::SetEnableSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rb_ui::SetEnableSrvRequest> should match 
// service_traits::DataType< ::rb_ui::SetEnableSrv > 
template<>
struct DataType< ::rb_ui::SetEnableSrvRequest>
{
  static const char* value()
  {
    return DataType< ::rb_ui::SetEnableSrv >::value();
  }
  static const char* value(const ::rb_ui::SetEnableSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rb_ui::SetEnableSrvResponse> should match 
// service_traits::MD5Sum< ::rb_ui::SetEnableSrv > 
template<>
struct MD5Sum< ::rb_ui::SetEnableSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rb_ui::SetEnableSrv >::value();
  }
  static const char* value(const ::rb_ui::SetEnableSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rb_ui::SetEnableSrvResponse> should match 
// service_traits::DataType< ::rb_ui::SetEnableSrv > 
template<>
struct DataType< ::rb_ui::SetEnableSrvResponse>
{
  static const char* value()
  {
    return DataType< ::rb_ui::SetEnableSrv >::value();
  }
  static const char* value(const ::rb_ui::SetEnableSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RB_UI_MESSAGE_SETENABLESRV_H
