// Generated by gencpp from file rb_ui/SetEnableSrvRequest.msg
// DO NOT EDIT!


#ifndef RB_UI_MESSAGE_SETENABLESRVREQUEST_H
#define RB_UI_MESSAGE_SETENABLESRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rb_ui
{
template <class ContainerAllocator>
struct SetEnableSrvRequest_
{
  typedef SetEnableSrvRequest_<ContainerAllocator> Type;

  SetEnableSrvRequest_()
    : enable(false)  {
    }
  SetEnableSrvRequest_(const ContainerAllocator& _alloc)
    : enable(false)  {
  (void)_alloc;
    }



   typedef uint8_t _enable_type;
  _enable_type enable;





  typedef boost::shared_ptr< ::rb_ui::SetEnableSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rb_ui::SetEnableSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetEnableSrvRequest_

typedef ::rb_ui::SetEnableSrvRequest_<std::allocator<void> > SetEnableSrvRequest;

typedef boost::shared_ptr< ::rb_ui::SetEnableSrvRequest > SetEnableSrvRequestPtr;
typedef boost::shared_ptr< ::rb_ui::SetEnableSrvRequest const> SetEnableSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rb_ui::SetEnableSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rb_ui::SetEnableSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rb_ui

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rb_ui::SetEnableSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rb_ui::SetEnableSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rb_ui::SetEnableSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rb_ui::SetEnableSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rb_ui::SetEnableSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rb_ui::SetEnableSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rb_ui::SetEnableSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8c1211af706069c994c06e00eb59ac9e";
  }

  static const char* value(const ::rb_ui::SetEnableSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8c1211af706069c9ULL;
  static const uint64_t static_value2 = 0x94c06e00eb59ac9eULL;
};

template<class ContainerAllocator>
struct DataType< ::rb_ui::SetEnableSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rb_ui/SetEnableSrvRequest";
  }

  static const char* value(const ::rb_ui::SetEnableSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rb_ui::SetEnableSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool enable\n\
";
  }

  static const char* value(const ::rb_ui::SetEnableSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rb_ui::SetEnableSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.enable);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetEnableSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rb_ui::SetEnableSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rb_ui::SetEnableSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "enable: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RB_UI_MESSAGE_SETENABLESRVREQUEST_H
