// Generated by gencpp from file rb_ui/SetEnableSrvResponse.msg
// DO NOT EDIT!


#ifndef RB_UI_MESSAGE_SETENABLESRVRESPONSE_H
#define RB_UI_MESSAGE_SETENABLESRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rb_ui
{
template <class ContainerAllocator>
struct SetEnableSrvResponse_
{
  typedef SetEnableSrvResponse_<ContainerAllocator> Type;

  SetEnableSrvResponse_()
    : finsh(false)  {
    }
  SetEnableSrvResponse_(const ContainerAllocator& _alloc)
    : finsh(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finsh_type;
  _finsh_type finsh;





  typedef boost::shared_ptr< ::rb_ui::SetEnableSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rb_ui::SetEnableSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetEnableSrvResponse_

typedef ::rb_ui::SetEnableSrvResponse_<std::allocator<void> > SetEnableSrvResponse;

typedef boost::shared_ptr< ::rb_ui::SetEnableSrvResponse > SetEnableSrvResponsePtr;
typedef boost::shared_ptr< ::rb_ui::SetEnableSrvResponse const> SetEnableSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rb_ui::SetEnableSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rb_ui::SetEnableSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rb_ui

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rb_ui::SetEnableSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rb_ui::SetEnableSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rb_ui::SetEnableSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rb_ui::SetEnableSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rb_ui::SetEnableSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rb_ui::SetEnableSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rb_ui::SetEnableSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8a4e67dead335a6c7b4b266de93bffd9";
  }

  static const char* value(const ::rb_ui::SetEnableSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8a4e67dead335a6cULL;
  static const uint64_t static_value2 = 0x7b4b266de93bffd9ULL;
};

template<class ContainerAllocator>
struct DataType< ::rb_ui::SetEnableSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rb_ui/SetEnableSrvResponse";
  }

  static const char* value(const ::rb_ui::SetEnableSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rb_ui::SetEnableSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool finsh\n\
\n\
";
  }

  static const char* value(const ::rb_ui::SetEnableSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rb_ui::SetEnableSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finsh);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetEnableSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rb_ui::SetEnableSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rb_ui::SetEnableSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "finsh: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finsh);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RB_UI_MESSAGE_SETENABLESRVRESPONSE_H
