// Generated by gencpp from file rbconnui_bridge/rb_ArrayAndBool.msg
// DO NOT EDIT!


#ifndef RBCONNUI_BRIDGE_MESSAGE_RB_ARRAYANDBOOL_H
#define RBCONNUI_BRIDGE_MESSAGE_RB_ARRAYANDBOOL_H

#include <ros/service_traits.h>


#include <rbconnui_bridge/rb_ArrayAndBoolRequest.h>
#include <rbconnui_bridge/rb_ArrayAndBoolResponse.h>


namespace rbconnui_bridge
{

struct rb_ArrayAndBool
{

typedef rb_ArrayAndBoolRequest Request;
typedef rb_ArrayAndBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rb_ArrayAndBool
} // namespace rbconnui_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbconnui_bridge::rb_ArrayAndBool > {
  static const char* value()
  {
    return "e9689b9c66e8f3509d77fd7da204e850";
  }

  static const char* value(const ::rbconnui_bridge::rb_ArrayAndBool&) { return value(); }
};

template<>
struct DataType< ::rbconnui_bridge::rb_ArrayAndBool > {
  static const char* value()
  {
    return "rbconnui_bridge/rb_ArrayAndBool";
  }

  static const char* value(const ::rbconnui_bridge::rb_ArrayAndBool&) { return value(); }
};


// service_traits::MD5Sum< ::rbconnui_bridge::rb_ArrayAndBoolRequest> should match 
// service_traits::MD5Sum< ::rbconnui_bridge::rb_ArrayAndBool > 
template<>
struct MD5Sum< ::rbconnui_bridge::rb_ArrayAndBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbconnui_bridge::rb_ArrayAndBool >::value();
  }
  static const char* value(const ::rbconnui_bridge::rb_ArrayAndBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbconnui_bridge::rb_ArrayAndBoolRequest> should match 
// service_traits::DataType< ::rbconnui_bridge::rb_ArrayAndBool > 
template<>
struct DataType< ::rbconnui_bridge::rb_ArrayAndBoolRequest>
{
  static const char* value()
  {
    return DataType< ::rbconnui_bridge::rb_ArrayAndBool >::value();
  }
  static const char* value(const ::rbconnui_bridge::rb_ArrayAndBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbconnui_bridge::rb_ArrayAndBoolResponse> should match 
// service_traits::MD5Sum< ::rbconnui_bridge::rb_ArrayAndBool > 
template<>
struct MD5Sum< ::rbconnui_bridge::rb_ArrayAndBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbconnui_bridge::rb_ArrayAndBool >::value();
  }
  static const char* value(const ::rbconnui_bridge::rb_ArrayAndBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbconnui_bridge::rb_ArrayAndBoolResponse> should match 
// service_traits::DataType< ::rbconnui_bridge::rb_ArrayAndBool > 
template<>
struct DataType< ::rbconnui_bridge::rb_ArrayAndBoolResponse>
{
  static const char* value()
  {
    return DataType< ::rbconnui_bridge::rb_ArrayAndBool >::value();
  }
  static const char* value(const ::rbconnui_bridge::rb_ArrayAndBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBCONNUI_BRIDGE_MESSAGE_RB_ARRAYANDBOOL_H
