// Generated by gencpp from file rbconnui_bridge/rb_ArrayAndBoolResponse.msg
// DO NOT EDIT!


#ifndef RBCONNUI_BRIDGE_MESSAGE_RB_ARRAYANDBOOLRESPONSE_H
#define RBCONNUI_BRIDGE_MESSAGE_RB_ARRAYANDBOOLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbconnui_bridge
{
template <class ContainerAllocator>
struct rb_ArrayAndBoolResponse_
{
  typedef rb_ArrayAndBoolResponse_<ContainerAllocator> Type;

  rb_ArrayAndBoolResponse_()
    : respond(false)  {
    }
  rb_ArrayAndBoolResponse_(const ContainerAllocator& _alloc)
    : respond(false)  {
  (void)_alloc;
    }



   typedef uint8_t _respond_type;
  _respond_type respond;





  typedef boost::shared_ptr< ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator> const> ConstPtr;

}; // struct rb_ArrayAndBoolResponse_

typedef ::rbconnui_bridge::rb_ArrayAndBoolResponse_<std::allocator<void> > rb_ArrayAndBoolResponse;

typedef boost::shared_ptr< ::rbconnui_bridge::rb_ArrayAndBoolResponse > rb_ArrayAndBoolResponsePtr;
typedef boost::shared_ptr< ::rbconnui_bridge::rb_ArrayAndBoolResponse const> rb_ArrayAndBoolResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rbconnui_bridge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f386576e317fabd22f70a14e46dc82ae";
  }

  static const char* value(const ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf386576e317fabd2ULL;
  static const uint64_t static_value2 = 0x2f70a14e46dc82aeULL;
};

template<class ContainerAllocator>
struct DataType< ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbconnui_bridge/rb_ArrayAndBoolResponse";
  }

  static const char* value(const ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool respond\n\
\n\
";
  }

  static const char* value(const ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.respond);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rb_ArrayAndBoolResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbconnui_bridge::rb_ArrayAndBoolResponse_<ContainerAllocator>& v)
  {
    s << indent << "respond: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.respond);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBCONNUI_BRIDGE_MESSAGE_RB_ARRAYANDBOOLRESPONSE_H
