// Generated by gencpp from file rbconnui_bridge/rb_DoubleBool.msg
// DO NOT EDIT!


#ifndef RBCONNUI_BRIDGE_MESSAGE_RB_DOUBLEBOOL_H
#define RBCONNUI_BRIDGE_MESSAGE_RB_DOUBLEBOOL_H

#include <ros/service_traits.h>


#include <rbconnui_bridge/rb_DoubleBoolRequest.h>
#include <rbconnui_bridge/rb_DoubleBoolResponse.h>


namespace rbconnui_bridge
{

struct rb_DoubleBool
{

typedef rb_DoubleBoolRequest Request;
typedef rb_DoubleBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rb_DoubleBool
} // namespace rbconnui_bridge


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rbconnui_bridge::rb_DoubleBool > {
  static const char* value()
  {
    return "f33163c172ac2891a975961a1d79e44e";
  }

  static const char* value(const ::rbconnui_bridge::rb_DoubleBool&) { return value(); }
};

template<>
struct DataType< ::rbconnui_bridge::rb_DoubleBool > {
  static const char* value()
  {
    return "rbconnui_bridge/rb_DoubleBool";
  }

  static const char* value(const ::rbconnui_bridge::rb_DoubleBool&) { return value(); }
};


// service_traits::MD5Sum< ::rbconnui_bridge::rb_DoubleBoolRequest> should match 
// service_traits::MD5Sum< ::rbconnui_bridge::rb_DoubleBool > 
template<>
struct MD5Sum< ::rbconnui_bridge::rb_DoubleBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rbconnui_bridge::rb_DoubleBool >::value();
  }
  static const char* value(const ::rbconnui_bridge::rb_DoubleBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbconnui_bridge::rb_DoubleBoolRequest> should match 
// service_traits::DataType< ::rbconnui_bridge::rb_DoubleBool > 
template<>
struct DataType< ::rbconnui_bridge::rb_DoubleBoolRequest>
{
  static const char* value()
  {
    return DataType< ::rbconnui_bridge::rb_DoubleBool >::value();
  }
  static const char* value(const ::rbconnui_bridge::rb_DoubleBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rbconnui_bridge::rb_DoubleBoolResponse> should match 
// service_traits::MD5Sum< ::rbconnui_bridge::rb_DoubleBool > 
template<>
struct MD5Sum< ::rbconnui_bridge::rb_DoubleBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rbconnui_bridge::rb_DoubleBool >::value();
  }
  static const char* value(const ::rbconnui_bridge::rb_DoubleBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rbconnui_bridge::rb_DoubleBoolResponse> should match 
// service_traits::DataType< ::rbconnui_bridge::rb_DoubleBool > 
template<>
struct DataType< ::rbconnui_bridge::rb_DoubleBoolResponse>
{
  static const char* value()
  {
    return DataType< ::rbconnui_bridge::rb_DoubleBool >::value();
  }
  static const char* value(const ::rbconnui_bridge::rb_DoubleBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RBCONNUI_BRIDGE_MESSAGE_RB_DOUBLEBOOL_H
