// Generated by gencpp from file rbconnui_bridge/rb_DoubleBoolRequest.msg
// DO NOT EDIT!


#ifndef RBCONNUI_BRIDGE_MESSAGE_RB_DOUBLEBOOLREQUEST_H
#define RBCONNUI_BRIDGE_MESSAGE_RB_DOUBLEBOOLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rbconnui_bridge
{
template <class ContainerAllocator>
struct rb_DoubleBoolRequest_
{
  typedef rb_DoubleBoolRequest_<ContainerAllocator> Type;

  rb_DoubleBoolRequest_()
    : request(false)  {
    }
  rb_DoubleBoolRequest_(const ContainerAllocator& _alloc)
    : request(false)  {
  (void)_alloc;
    }



   typedef uint8_t _request_type;
  _request_type request;





  typedef boost::shared_ptr< ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator> const> ConstPtr;

}; // struct rb_DoubleBoolRequest_

typedef ::rbconnui_bridge::rb_DoubleBoolRequest_<std::allocator<void> > rb_DoubleBoolRequest;

typedef boost::shared_ptr< ::rbconnui_bridge::rb_DoubleBoolRequest > rb_DoubleBoolRequestPtr;
typedef boost::shared_ptr< ::rbconnui_bridge::rb_DoubleBoolRequest const> rb_DoubleBoolRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rbconnui_bridge

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f7e5ad6ab0ddf42c5727a195315a470";
  }

  static const char* value(const ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f7e5ad6ab0ddf42ULL;
  static const uint64_t static_value2 = 0xc5727a195315a470ULL;
};

template<class ContainerAllocator>
struct DataType< ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rbconnui_bridge/rb_DoubleBoolRequest";
  }

  static const char* value(const ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool request\n\
";
  }

  static const char* value(const ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rb_DoubleBoolRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rbconnui_bridge::rb_DoubleBoolRequest_<ContainerAllocator>& v)
  {
    s << indent << "request: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.request);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RBCONNUI_BRIDGE_MESSAGE_RB_DOUBLEBOOLREQUEST_H
