// Generated by gencpp from file rb_msg/rbImageList.msg
// DO NOT EDIT!


#ifndef RB_MSG_MESSAGE_RBIMAGELIST_H
#define RB_MSG_MESSAGE_RBIMAGELIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/Image.h>

namespace rb_msg
{
template <class ContainerAllocator>
struct rbImageList_
{
  typedef rbImageList_<ContainerAllocator> Type;

  rbImageList_()
    : imagelist()  {
    }
  rbImageList_(const ContainerAllocator& _alloc)
    : imagelist(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::sensor_msgs::Image_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sensor_msgs::Image_<ContainerAllocator> >::other >  _imagelist_type;
  _imagelist_type imagelist;





  typedef boost::shared_ptr< ::rb_msg::rbImageList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rb_msg::rbImageList_<ContainerAllocator> const> ConstPtr;

}; // struct rbImageList_

typedef ::rb_msg::rbImageList_<std::allocator<void> > rbImageList;

typedef boost::shared_ptr< ::rb_msg::rbImageList > rbImageListPtr;
typedef boost::shared_ptr< ::rb_msg::rbImageList const> rbImageListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rb_msg::rbImageList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rb_msg::rbImageList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rb_msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rb_msg': ['/home/wangneng/rb_msg/src/rb_msg/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rb_msg::rbImageList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rb_msg::rbImageList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rb_msg::rbImageList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rb_msg::rbImageList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rb_msg::rbImageList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rb_msg::rbImageList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rb_msg::rbImageList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d72f9c5c0957b5aa348eaf6873546dd";
  }

  static const char* value(const ::rb_msg::rbImageList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d72f9c5c0957b5aULL;
  static const uint64_t static_value2 = 0xa348eaf6873546ddULL;
};

template<class ContainerAllocator>
struct DataType< ::rb_msg::rbImageList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rb_msg/rbImageList";
  }

  static const char* value(const ::rb_msg::rbImageList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rb_msg::rbImageList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_msgs/Image[] imagelist\n\
\n\
================================================================================\n\
MSG: sensor_msgs/Image\n\
# This message contains an uncompressed image\n\
# (0, 0) is at top-left corner of image\n\
#\n\
\n\
Header header        # Header timestamp should be acquisition time of image\n\
                     # Header frame_id should be optical frame of camera\n\
                     # origin of frame should be optical center of camera\n\
                     # +x should point to the right in the image\n\
                     # +y should point down in the image\n\
                     # +z should point into to plane of the image\n\
                     # If the frame_id here and the frame_id of the CameraInfo\n\
                     # message associated with the image conflict\n\
                     # the behavior is undefined\n\
\n\
uint32 height         # image height, that is, number of rows\n\
uint32 width          # image width, that is, number of columns\n\
\n\
# The legal values for encoding are in file src/image_encodings.cpp\n\
# If you want to standardize a new string format, join\n\
# ros-users@lists.sourceforge.net and send an email proposing a new encoding.\n\
\n\
string encoding       # Encoding of pixels -- channel meaning, ordering, size\n\
                      # taken from the list of strings in include/sensor_msgs/image_encodings.h\n\
\n\
uint8 is_bigendian    # is this data bigendian?\n\
uint32 step           # Full row length in bytes\n\
uint8[] data          # actual matrix data, size is (step * rows)\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::rb_msg::rbImageList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rb_msg::rbImageList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.imagelist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rbImageList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rb_msg::rbImageList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rb_msg::rbImageList_<ContainerAllocator>& v)
  {
    s << indent << "imagelist[]" << std::endl;
    for (size_t i = 0; i < v.imagelist.size(); ++i)
    {
      s << indent << "  imagelist[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sensor_msgs::Image_<ContainerAllocator> >::stream(s, indent + "    ", v.imagelist[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RB_MSG_MESSAGE_RBIMAGELIST_H
